[package]
name = "rustbot"
version = "0.1.2"
authors = ["hyperchessbot <hyperchessbot@gmail.com>"]
edition = "2018"

[dependencies]
lichessbot = "0.1.18"
env_logger = "0.8.2"

[dependencies.tokio]
version = "1.0.1"
features = ["full"]

[[bin]]
name = "rustbot"
path = "src/main.rs"
